### ISSUE TITLE
Getting type error in fit_predict of K-prototypes

### ISSUE THREAD

**Issue by sharma-ji** [nicodv/kmodes#97] opened 2019-01-09 07:42 UTC
Initialization method and algorithm are deterministic. Setting n_init to 1.
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run: 1, iteration: 1/100, moves: 14671, ncost: 1410.2037399601834
Run: 1, iteration: 2/100, moves: 2844, ncost: 1410.2037389942027
Run: 1, iteration: 3/100, moves: 169, ncost: 1410.203738989078
Run: 1, iteration: 4/100, moves: 24, ncost: 1410.203738988245
Run: 1, iteration: 5/100, moves: 0, ncost: 1410.203738988245
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-158-06e1bc9ba83c> in <module>()
      1 kproto = KPrototypes(n_clusters=4,init='Cao',verbose=True)
----> 2 clusters = kproto.fit_predict(temp,categorical=[2])

C:\Users\Mukul.Sharma\AppData\Local\Continuum\Anaconda3\lib\site-packages\kmodes\kmodes.py in fit_predict(self, X, y, **kwargs)
    374         predict(X).
    375         """
--> 376         return self.fit(X, **kwargs).predict(X, **kwargs)
    377 
    378     def predict(self, X, **kwargs):

C:\Users\Mukul.Sharma\AppData\Local\Continuum\Anaconda3\lib\site-packages\kmodes\kprototypes.py in predict(self, X, categorical)
    436         assert hasattr(self, '_enc_cluster_centroids'), "Model not yet fitted."
    437 
--> 438         Xnum, Xcat = _split_num_cat(X, categorical)
    439         Xnum, Xcat = check_array(Xnum), check_array(Xcat, dtype=None)
    440         Xcat, _ = encode_features(Xcat, enc_map=self._enc_map)

C:\Users\Mukul.Sharma\AppData\Local\Continuum\Anaconda3\lib\site-packages\kmodes\kprototypes.py in _split_num_cat(X, categorical)
     42     :param categorical: Indices of categorical columns
     43     """
---> 44     Xnum = np.asanyarray(X[:, [ii for ii in range(X.shape[1])
     45                                if ii not in categorical]]).astype(np.float64)
     46     Xcat = np.asanyarray(X[:, categorical])

C:\Users\Mukul.Sharma\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2060             return self._getitem_multilevel(key)
   2061         else:
-> 2062             return self._getitem_column(key)
   2063 
   2064     def _getitem_column(self, key):

C:\Users\Mukul.Sharma\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\frame.py in _getitem_column(self, key)
   2067         # get column
   2068         if self.columns.is_unique:
-> 2069             return self._get_item_cache(key)
   2070 
   2071         # duplicate columns & possible reduce dimensionality

C:\Users\Mukul.Sharma\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\generic.py in _get_item_cache(self, item)
   1530         """Return the cached item, item represents a label indexer."""
   1531         cache = self._item_cache
-> 1532         res = cache.get(item)
   1533         if res is None:
   1534             values = self._data.get(item)

TypeError: unhashable type: 'slice'

**Comment by nicodv** [comment] 2019-01-09 19:24
Try giving the algorithm a numpy array, not a pandas DataFrame, by doing `temp.values`.

**Comment by nicodv** [comment] 2019-01-10 19:57
Duplicate of https://github.com/nicodv/kmodes/issues/67

**Closed by nicodv** 2019-01-10 19:57 UTC
