### ISSUE TITLE
Got a value error while doing clustering

### ISSUE THREAD

**Issue by sharma-ji** [nicodv/kmodes#98] opened 2019-01-10 07:41 UTC
code: 
`kproto=  KPrototypes(n_clusters=4,init='Huang',verbose=True)
cluster_labels = kproto.fit_predict(cleaned_new.values,categorical=[0,2,4,5,8,9,10])`

**Error**
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-158-6f2d7a0e3c9a> in <module>()
      1 kproto=  KPrototypes(n_clusters=4,init='Huang',verbose=True)
----> 2 cluster_labels = kproto.fit_predict(cleaned_new.values,categorical=[0,2,4,5,8,9,10])

C:\Users\Mukul.Sharma\AppData\Local\Continuum\Anaconda3\lib\site-packages\kmodes\kmodes.py in fit_predict(self, X, y, **kwargs)
    374         predict(X).
    375         """
--> 376         return self.fit(X, **kwargs).predict(X, **kwargs)
    377 
    378     def predict(self, X, **kwargs):

C:\Users\Mukul.Sharma\AppData\Local\Continuum\Anaconda3\lib\site-packages\kmodes\kprototypes.py in fit(self, X, y, categorical)
    417                                                     self.init,
    418                                                     self.n_init,
--> 419                                                     self.verbose)
    420         return self
    421 

C:\Users\Mukul.Sharma\AppData\Local\Continuum\Anaconda3\lib\site-packages\kmodes\kprototypes.py in k_prototypes(X, categorical, n_clusters, max_iter, num_dissim, cat_dissim, gamma, init, n_init, verbose)
    268             elif init_tries == RAISE_INIT_TRIES:
    269                 raise ValueError(
--> 270                     "Clustering algorithm could not initialize. "
    271                     "Consider assigning the initial clusters manually."
    272                 )

ValueError: Clustering algorithm could not initialize. Consider assigning the initial clusters manually.

**Comment by nicodv** [comment] 2019-01-10 20:00
This looks like something specific to your data. You'll need to do more analysis of your data to see if k-modes is a valid approach.

Closing this as this is expected behavior when a data set is not suitable for clustering.

**Closed by nicodv** 2019-01-10 20:00 UTC
