### ISSUE TITLE
API Document needed~

### ISSUE THREAD

**Issue by mrlonely001** [nicodv/kmodes#126] opened 2019-05-13 03:38 UTC
Thanks for your implementation of  k-mode and k-prototype .  I strongly recommend you  adding some document about the API of two clustering method，for this project will have a wider usage.

**Comment by nicodv** [comment] 2019-05-16 04:45
Agreed. :) Duplicate of https://github.com/nicodv/kmodes/issues/28

**Closed by nicodv** 2019-05-16 04:45 UTC
Labels: enhancement
