### ISSUE TITLE
 TypeError: unhashable type: 'slice'

### ISSUE THREAD

**Issue by Upendran-Akshay** [nicodv/kmodes#72] opened 2018-05-21 05:36 UTC
Hi,

when i commit the code below:

from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = "Nan", strategy = "mean",axis = 0)
imputer = imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

it can't run with the "  TypeError: unhashable type: 'slice'". could you please tell me how can solve this problem? Thank very much!

**Comment by nicodv** [comment] 2018-05-21 17:58
Does this even have anything to do with `kmodes` at all? Closing this until you can prove otherwise.

**Closed by nicodv** 2018-05-21 17:58 UTC

**Comment by Upendran-Akshay** [comment] 2018-05-22 05:09
Hi,

when i commit the code below:

from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = "Nan", strategy = "mean",axis = 0)
imputer = imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

it can't run with the " TypeError: unhashable type: 'slice'". could you please tell me how can solve this problem? Thank very much!

**Comment by nicodv** [comment] 2019-01-10 20:58
Duplicate of: https://github.com/nicodv/kmodes/issues/67
